services:
  nginx:
    build:
      context: ./nginx
    image: sagu-nginx:latest
    container_name: sagu-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true
