name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042704722049.dkr.ecr.us-east-1.amazonaws.com

      - name: Install Docker Compose (v2)
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build images using Docker Compose
        run: |
          docker compose --env-file .env -f docker-compose.yml build

      - name: Push Docker images to ECR
        run: |
          docker compose --env-file .env -f docker-compose.yml push

  connect:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Login to ECR
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Conexão estabelecida com sucesso no EC2"
            uname -a
            whoami
            echo "Testando conectividade com AWS ECR..."
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042704722049.dkr.ecr.us-east-1.amazonaws.com

  deploy:
    needs: [connect]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application on EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Indo para a pasta da aplicação..."
            cd /home/ubuntu/sagu-api || { echo "Falha ao acessar o diretório"; exit 1; }
            echo "Atualizando containers com a nova imagem..."
            docker compose pull
            docker image prune -f
            docker compose up -d
            echo "Deploy finalizado com sucesso!"
