name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042704722049.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image
        run: |
          docker compose -f docker-compose.yml build
          docker tag sagu-api-web:latest 042704722049.dkr.ecr.us-east-1.amazonaws.com/sagu-api:latest
          docker push 042704722049.dkr.ecr.us-east-1.amazonaws.com/sagu-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            echo "Conectando no EC2..."
            cd /home/ubuntu/sagu-api || { echo "Diretório não encontrado"; exit 1; }

            echo "Fazendo login no ECR..."
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042704722049.dkr.ecr.us-east-1.amazonaws.com

            echo "Atualizando imagem..."
            docker pull 042704722049.dkr.ecr.us-east-1.amazonaws.com/sagu-api:latest

            echo "Derrubando containers antigos..."
            docker compose -f docker-compose.api.yml down

            echo "Subindo containers atualizados..."
            docker compose -f docker-compose.api.yml up -d

            echo "Deploy finalizado!"
