name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042704722049.dkr.ecr.us-east-1.amazonaws.com

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Tag Docker image
        run: docker tag sagu-api_web:latest 042704722049.dkr.ecr.us-east-1.amazonaws.com/sagu-api:latest

      - name: Push Docker image to ECR
        run: docker push 042704722049.dkr.ecr.us-east-1.amazonaws.com/sagu-api:latest

  connect:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Login to ECR (with debug)
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          debug: true   # <-- DEBUG ATIVADO
          script: |
            echo "Conexão estabelecida com sucesso no EC2"
            uname -a
            whoami
            echo "Testando conectividade com AWS ECR..."
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042704722049.dkr.ecr.us-east-1.amazonaws.com

  deploy:
    needs: connect
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application on EC2 (with debug)
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          debug: true 
          script: |
            echo "Indo para a pasta da aplicação..."
            cd /path/to/your/app || { echo "Falha ao acessar o diretório"; exit 1; }
            echo "Atualizando container com a nova imagem..."
            docker pull 042704722049.dkr.ecr.us-east-1.amazonaws.com/sagu-api:latest
            docker-compose up -d
            echo "Deploy finalizado!"
