name: Conectar ao EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  ssh-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Chave privada do EC2 armazenada no Secrets do GitHub
        chmod 600 ~/.ssh/id_rsa  # Ajusta as permissões da chave privada para segurança

    - name: Adicionar IP da instância EC2 ao known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts  # Adiciona o IP da instância EC2 ao arquivo known_hosts

    - name: Conectar via SSH ao EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} "echo 'Conectado com sucesso ao EC2!'"
